DROP DATABASE IF EXISTS FOODSTOREDB;

CREATE DATABASE FOODSTOREDB
  CHARSET = 'utf8'
  COLLATE = 'utf8_general_ci';

-- USERS --

CREATE TABLE FOODSTOREDB.USERS
(
  ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(128)    NOT NULL,
  EMAIL       VARCHAR(25)     NOT NULL UNIQUE,
  PASSWORD    VARCHAR(25)     NOT NULL,
  ROLE        VARCHAR(10)     NOT NULL
);

CREATE TABLE FOODSTOREDB.ADDRESSES
(
  ID             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COUNTRY        VARCHAR (64)    NOT NULL,
  CITY           VARCHAR (64)    NOT NULL,
  STREET_ADDRESS VARCHAR (128)   NOT NULL,
  USER_ID        BIGINT UNSIGNED NOT NULL,
  CONSTRAINT ADDRESSES_USERS_FK
  FOREIGN KEY (USER_ID) REFERENCES FOODSTOREDB.USERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE FOODSTOREDB.FEEDBACK
(
  ID             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USER_ID        BIGINT UNSIGNED NOT NULL,
  USER_COMMENT   VARCHAR (200)   NOT NULL,
  CONSTRAINT FEEDBACK_USERS_FK
  FOREIGN KEY (USER_ID) REFERENCES FOODSTOREDB.USERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE FOODSTOREDB.ITEMS
(
  ID            BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME          VARCHAR(128)     NOT NULL,
  S_PRICE       FLOAT,
  M_PRICE       FLOAT            NOT NULL,
  L_PRICE       FLOAT,
  URL           VARCHAR(128)     NOT NULL
);

CREATE TABLE FOODSTOREDB.ORDERS
(
  ID                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TOTAL_PRICE       FLOAT           NOT NULL,
  ORDER_DATE        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USER_ID           BIGINT UNSIGNED NOT NULL,
  CONSTRAINT ORDERS_USERS_FK
  FOREIGN KEY (USER_ID) REFERENCES FOODSTOREDB.USERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

CREATE TABLE FOODSTOREDB.ORDERS_ITEMS
(
  ORDER_ID      BIGINT UNSIGNED   NOT NULL,
  ITEM_ID       BIGINT UNSIGNED   NOT NULL,
  ITEM_SIZE     VARCHAR(10)       NOT NULL,
  QUANTITY      INT               NOT NULL DEFAULT 1,
  
  PRIMARY KEY(ORDER_ID, ITEM_ID, ITEM_SIZE),
  
  CONSTRAINT ORDERS_ITEMS_ORDERID_FK
  FOREIGN KEY (ORDER_ID) REFERENCES FOODSTOREDB.ORDERS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT ORDERS_ITEMS_ITEMID_FK
  FOREIGN KEY (ITEM_ID) REFERENCES FOODSTOREDB.ITEMS (ID)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);
